config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  resources :areas
  resources :items do
    collection do
      get 'order'
      get 'check_order'
      get 'crash_order'
      get 'receive_order'
      get 'approval_order'
      get 'my_store'
    end
    resources :chats
  end
  resources :wallets do
    collection do
      get 'check_receipts'
      get 'change_gift'
    end
  end
  resources :orders
  resources :menus do
    collection do
      get 'give'
      get 'take'
      get 'point'
      get 'how_to_use'
    end
  end
  resources :gifts do
    collection do
      get 'watching_ads'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  belongs_to :user

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :message, presence: true
end

app/models/gift.rb
class Gift < ApplicationRecord
  belongs_to :user

  validates :gift_id, :point, :name, :address, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :orders
  has_one :chat

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :wash_power
  belongs_to :status

  validates :wash_power_id, :status_id, :comment, :address, :point, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :item
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :wallet
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '準備中' },
    { id: 2, name: '受付中' },
    { id: 3, name: '本日終了' },
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :area
  has_one :wallet
  has_many :chats
  has_many :gifts
  has_many :items
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
  has_many :receipts
end

app/models/wash_power.rb
class WashPower < ActiveHash::Base
  self.data = [
    { id: 1, name: '4.5Kg' },
    { id: 2, name: '5Kg' },
    { id: 3, name: '6Kg' },
    { id: 4, name: '7Kg' },
    { id: 5, name: '8Kg' },
    { id: 6, name: '9Kg' },
    { id: 7, name: '10Kg' },
    { id: 8, name: '11Kg' },
    { id: 9, name: '12Kg' },
  ]

  include ActiveHash::Associations
  has_many :items
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  def new
    if user_signed_in?
      @area = Area.new
    else
      redirect_to new_user_session_path
    end
  end

  def create
    area = Area.new(area_params)
    if area.valid?
      if Area.find_by(user_id: current_user.id) != nil
        Area.find_by(user_id: current_user.id).destroy
      end
      Area.create(area_params)
      redirect_to :root
    else
      @area = Area.new(area_params)
      render :new
    end
  end

  private

  def area_params
    params.require(:area).permit(:address, :user_id, :latitude, :longitude).merge(user_id: current_user.id)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def new
    @chat = Chat.new
    @item = Item.find_by(id: params[:item_id])
    @chats = Chat.where(item_id: params[:item_id])
  end

  def create
    if Chat.new(chat_params).valid?
      Chat.create(chat_params)
      redirect_to new_item_chat_path(params[:item_id])
    else
      redirect_to new_item_chat_path(params[:item_id])
    end
  end

  private

  def chat_params
    params.require(:chat).permit(:message).merge(user_id: current_user.id).merge(item_id: params[:item_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tad5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= include_gon %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
</div>

app/views/shared/_header.html.erb
<div class="header">
  <div class="title">
    <%= link_to "Share Laundry", root_path, style:"text-decoration: none;" %>
  </div>
  <div class="header_R">
    <% if user_signed_in? %>
    <div class="user_name">
      <b>ようこそ<%= "#{current_user.email}"%>さん</b>
    </div>
    <div>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"btn-shared"%>
    </div>

    <% else %>
    <div class="user_name">
      <b>ようこそゲストさん</b>
    </div>
    <div>
      <a href="/users/sign_in" class="btn-shared">ログイン</a>
    </div>
    <% end %>

  </div>
</div>

app/views/shared/_menu.html.erb
<div class="menu">
  <div class="menu_1">
    <p>現在のポイント</p>
    <% if user_signed_in? %>
    <b style="font-size: 24px;"><%= "#{@my_wallet.point}" %>P</b>
    <% else %>
    <b style="font-size: 24px;">--- P</b>
    <% end %>
  </div>
  <div class="menu_2">
    <div>
      <a href="/" class="search_btn btn-shared"><b style="font-size: 18px;">トップページ</b>へ戻る</a>
    </div>
    <div>
      <a href="/wallets/show" class="search_btn btn-shared"><b style="font-size: 16px;">ポイントメニュー</b></a>
    </div>
  </div>
  <div class="menu_2">
    <div>
      <a href="/items/my_store" class="search_btn btn-shared"><b style="font-size: 16px;">提供中の</b>サービス一覧</a>
    </div>
    <div>
      <a href="/items/check_order" class="search_btn btn-shared"><b style="font-size: 16px;">送信したリクエスト</b>を確認</a>
    </div>
  </div>
  <div class="menu_2">
    <div>
      <a href="/items/new" class="search_btn btn-shared"><b style="font-size: 16px;">サービス</b>を提供</a>
    </div>
    <div>
      <a href="/items/receive_order" class="search_btn btn-shared"><b style="font-size: 16px;">受信したリクエスト</b>を確認</a>
    </div>
  </div>
</div>

app/views/shared/_menu2.html.erb
<div class="menu">
  <div class="menu_1">
    <p>現在のポイント</p>
    <% if user_signed_in? %>
    <b style="font-size: 24px;"><%= "#{@my_wallet.point}" %>P</b>
    <% else %>
    <b style="font-size: 24px;">--- P</b>
    <% end %>
  </div>
  <div class="menu_2">
    <div>
      <a href="/" class="search_btn btn-shared"><b style="font-size: 18px;">トップページ</b>へ戻る</a>
    </div>
    <div>
      <a href="/wallets/show" class="search_btn btn-shared"><b style="font-size: 16px;">ポイントメニュー</b></a>
    </div>
  </div>
  <div class="menu_2">
    <% if @item.user_id == current_user.id %>
    <div>
      <a href="/items/my_store" class="search_btn btn-shared"><b style="font-size: 16px;">提供中の</b>サービス一覧</a>
    </div>
    <% else %>
    <div>
      <%= link_to 'リクエストを送る', order_items_path(@item), class: "search_btn btn-shared", style:"font-weight: bold;" %>
    </div>
    <% end %>
    <div>
      <a href="/items/check_order" class="search_btn btn-shared"><b style="font-size: 16px;">送信したリクエスト</b>を確認</a>
    </div>
  </div>
  <div class="menu_2">
    <div>
      <a href="/items/new" class="search_btn btn-shared"><b style="font-size: 16px;">サービス</b>を提供</a>
    </div>
    <div>
      <a href="/items/receive_order" class="search_btn btn-shared"><b style="font-size: 16px;">受信したリクエスト</b>を確認</a>
    </div>
  </div>
</div>

app/views/shared/_menu_area.html.erb
<div class="menu">
  <div class="menu_1">
    <p>現在のポイント</p>
    <% if user_signed_in? %>
    <b style="font-size: 24px;"><%= "#{@my_wallet.point}" %>P</b>
    <% else %>
    <b style="font-size: 24px;">--- P</b>
    <% end %>
  </div>
  <div class="menu_2">
    <div>
      <a href="/" class="search_btn btn-shared"><b style="font-size: 18px;">トップページ</b>へ戻る</a>
    </div>
  </div>
  <div class="menu_2">
  </div>
  <div class="menu_2">
  </div>
</div>

app/views/shared/_menu_back_point.html.erb
<div class="menu">
  <div class="menu_1">
    <p>現在のポイント</p>
    <% if user_signed_in? %>
    <b style="font-size: 24px;"><%= "#{@my_wallet.point}" %>P</b>
    <% else %>
    <b style="font-size: 24px;">--- P</b>
    <% end %>
  </div>
  <div class="menu_2">
    <div>
      <a href="/menus/point" class="search_btn btn-shared"><b style="font-size: 16px;">ポイントメニュー</b></a>
    </div>
  </div>
</div>

app/views/shared/_menu_chat.html.erb
<div class="menu">
  <div class="menu_1">
    <p>現在のポイント</p>
    <% if user_signed_in? %>
    <b style="font-size: 24px;"><%= "#{@my_wallet.point}" %>P</b>
    <% else %>
    <b style="font-size: 24px;">--- P</b>
    <% end %>
  </div>
  <div class="menu_2">
    <div>
      <a href="/areas/new" class="search_btn btn-shared"><b style="font-size: 18px;">ご利用エリア</b>の変更</a>
    </div>
    <div>
      <a href="/wallets/show" class="search_btn btn-shared"><b style="font-size: 16px;">ポイントメニュー</b></a>
    </div>
  </div>
  <div class="menu_2">
    <div>
      <a href="/items/new" class="search_btn btn-shared"><b style="font-size: 16px;">サービス</b>を提供</a>
    </div>
    <div>
      <a href="/items/check_order" class="search_btn btn-shared"><b style="font-size: 16px;">送信したリクエスト</b>を確認</a>
    </div>
  </div>
  <div class="menu_2">
    <div>
      <a href="/items/receive_order" class="search_btn btn-shared"><b style="font-size: 16px;">受信したリクエスト</b>を確認</a>
    </div>
    <% if @item.user_id == current_user.id %>
    <% else %>
    <div>
      <%= link_to 'リクエストを送る', order_items_path(@item), class: "search_btn btn-shared", style:"font-weight: bold;" %>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_menu_give.html.erb
<div class="menu">
  <div class="menu_1">
    <p>現在のポイント</p>
    <% if user_signed_in? %>
    <b style="font-size: 24px;"><%= "#{@my_wallet.point}" %>P</b>
    <% else %>
    <b style="font-size: 24px;">--- P</b>
    <% end %>
  </div>
  <div class="menu_2">
    <div>
      <a href="/" class="search_btn btn-shared"><b style="font-size: 18px;">トップページ</b>へ戻る</a>
    </div>
    <div>
      <a href="/items/new" class="search_btn btn-shared"><b style="font-size: 16px;">サービス</b>を提供</a>
    </div>
  </div>
  <div class="menu_2">
    <div>
      <a href="/items/my_store" class="search_btn btn-shared"><b style="font-size: 16px;">提供中の</b>サービス一覧</a>
    </div>
    <div>
      <a href="/items/receive_order" class="search_btn btn-shared"><b style="font-size: 16px;">受信したリクエスト</b>を確認</a>
    </div>
  </div>
</div>

app/views/shared/_menu_point.html.erb
<div class="menu">
  <div class="menu_1">
    <p>現在のポイント</p>
    <% if user_signed_in? %>
    <b style="font-size: 24px;"><%= "#{@my_wallet.point}" %>P</b>
    <% else %>
    <b style="font-size: 24px;">--- P</b>
    <% end %>
  </div>
  <div class="menu_2">
    <div>
      <a href="/" class="search_btn btn-shared"><b style="font-size: 18px;">トップページ</b>へ戻る</a>
    </div>
    <div>
      <%= link_to '履歴を見る', check_receipts_wallets_path, class: "search_btn btn-shared", style:"font-size:20px; font-weight: bold;" %>
    </div>
  </div>
  <div class="menu_2">
    <div>
      <%= link_to 'ポイントを貯める　(広告視聴)', watching_ads_gifts_path, class: "search_btn btn-shared", style:"font-size: 14px; font-weight: bold;"%>
    </div>
    <div>
      <%= link_to 'ポイントを景品と交換', new_gift_path, class: "search_btn btn-shared", style:"font-weight: bold;" %>
    </div>
  </div>
</div>

app/views/shared/_menu_take.html.erb
<div class="menu">
  <div class="menu_1">
    <p>現在のポイント</p>
    <% if user_signed_in? %>
    <b style="font-size: 24px;"><%= "#{@my_wallet.point}" %>P</b>
    <% else %>
    <b style="font-size: 24px;">--- P</b>
    <% end %>
  </div>
  <div class="menu_2">
    <div>
      <a href="/" class="search_btn btn-shared"><b style="font-size: 18px;">トップページ</b>へ戻る</a>
    </div>
    <div>
      <a href="/menus/point" class="search_btn btn-shared"><b style="font-size: 16px;">ポイントメニュー</b></a>
    </div>
  </div>
  <div class="menu_2">
    <div>
      <a href="/items/check_order" class="search_btn btn-shared"><b style="font-size: 16px;">送信したリクエスト</b>を確認</a>
    </div>
  </div>
</div>

app/views/shared/_menu_take_co.html.erb
<div class="menu">
  <div class="menu_1">
    <p>現在のポイント</p>
    <% if user_signed_in? %>
    <b style="font-size: 24px;"><%= "#{@my_wallet.point}" %>P</b>
    <% else %>
    <b style="font-size: 24px;">--- P</b>
    <% end %>
  </div>
  <div class="menu_2">
    <div>
      <a href="/" class="search_btn btn-shared"><b style="font-size: 18px;">トップページ</b>へ戻る</a>
    </div>
    <div>
      <a href="/menus/point" class="search_btn btn-shared"><b style="font-size: 16px;">ポイントメニュー</b></a>
    </div>
  </div>
  <div class="menu_2">
    <div>
      <a href="/items/check_order" class="search_btn btn-shared"><b style="font-size: 16px;">送信したリクエスト</b>を確認</a>
    </div>
  </div>
</div>

app/views/shared/_menu_take_req.html.erb
<div class="menu">
  <div class="menu_1">
    <p>現在のポイント</p>
    <% if user_signed_in? %>
    <b style="font-size: 24px;"><%= "#{@my_wallet.point}" %>P</b>
    <% else %>
    <b style="font-size: 24px;">--- P</b>
    <% end %>
  </div>
  <div class="menu_2">
    <div>
      <a href="/" class="search_btn btn-shared"><b style="font-size: 18px;">トップページ</b>へ戻る</a>
    </div>
    <div>
      <a href="/menus/point" class="search_btn btn-shared"><b style="font-size: 16px;">ポイントメニュー</b></a>
    </div>
  </div>
  <div class="menu_2">
    <div>
      <%= link_to 'リクエストを送る', order_items_path(@item), class: "search_btn btn-shared", style:"font-weight: bold;" %>
    </div>
    <div>
      <a href="/items/check_order" class="search_btn btn-shared"><b style="font-size: 16px;">送信したリクエスト</b>を確認</a>
    </div>
  </div>
</div>

app/views/shared/_menu_top.html.erb
<div class="menu">
  <div class="menu_1">
    <p>現在のポイント</p>
    <% if user_signed_in? %>
    <b style="font-size: 24px;"><%= "#{@my_wallet.point}" %>P</b>
    <% else %>
    <b style="font-size: 24px;">--- P</b>
    <% end %>
  </div>
  <div class="menu_2">
    <div>
      <a href="/areas/new" class="search_btn btn-shared"><b style="font-size: 18px;">ご利用エリア</b>の変更</a>
    </div>
    <div>
      <a href="/menus/point" class="search_btn btn-shared"><b style="font-size: 16px;">ポイントメニュー</b></a>
    </div>
  </div>
  <div class="menu_2">
    <div>
      <a href="/menus/give" class="search_btn btn-shared">サービスを<b style="font-size: 20px;">提供</b>する</a>
    </div>
    <div>
      <a href="/menus/how_to_use" class="search_btn btn-shared"><b style="font-size: 32px;">?</b>使い方</a>
    </div>
  </div>
</div>