config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  resources :areas
  resources :items do
    collection do
      get 'order'
      get 'check_order'
      get 'crash_order'
      get 'receive_order'
      get 'approval_order'
      get 'my_store'
    end
    resources :chats
  end
  resources :wallets do
    collection do
      get 'check_receipts'
      get 'change_gift'
    end
  end
  resources :orders
  resources :menus do
    collection do
      get 'give'
      get 'take'
      get 'point'
      get 'how_to_use'
    end
  end
  resources :gifts do
    collection do
      get 'watching_ads'
    end
  end
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :message, presence: true
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def new
    @chat = Chat.new
    @item = Item.find_by(id: params[:item_id])
    @chats = Chat.where(item_id: params[:item_id])
  end

  def create
    if Chat.new(chat_params).valid?
      Chat.create(chat_params)
      redirect_to new_item_chat_path(params[:item_id])
    else
      redirect_to new_item_chat_path(params[:item_id])
    end
  end

  private

  def chat_params
    params.require(:chat).permit(:message).merge(user_id: current_user.id).merge(item_id: params[:item_id])
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_new_content.html.erb
<div class="content">
  <div class="content_header_daj">
    <p style="text-align:center"><%="#{@item.user.email}さんへの問い合わせ"%></p>
  </div>
  <div class="content_body_S">
    <div id="chats">
      <% @chats.each do |chat|%>
      <%if chat.user_id==current_user.id%>
      <p style="font-size: 8px; color: rgb(32, 206, 206);"><%=chat.created_at.strftime("%m月%d日 %H時%m分")%></p>
      <div class="mycomment">
        <p><%=chat.message%></p>
      </div>
      <%else%>
      <p style="font-size: 8px; color: rgb(32, 206, 206); text-align:left">
        <%=chat.created_at.strftime("%m月%d日 %H時%m分")%></p>
      <div class="fukidasi">
        <div class="faceicon" , style="font-size: 8px; color: rgb(32, 206, 206);">
          <%= "#{chat.user.email}"%>
        </div>
        <div class="chatting">
          <div class="says">
            <p><%=chat.message%></p>
          </div>
        </div>
      </div>
      <%end%>
      <%end%>
    </div>
  </div>
  <div class="content_footer">
    <div class="chat_form">
      <%= form_with model: @chat, url: item_chats_path, id:"send-form", local: true do |f|%>
      <%= f.text_field :message, class:"items-text", id:"message", placeholder:"入力してね", style:"width:30%;", maxlength:"40" %>
      <%= f.submit '送信', id:"send", class:"very_small_btn"%>
      <%end%>
    </div>
  </div>
</div>

app/views/chats/new.html.erb
<div class="outer_frame">
  <%= render "shared/header" %>
  <div class="inner_frame">
    <%= render "new_content" %>
    <% if @item.user_id == current_user.id %>
    <%= render "shared/menu_give" %>
    <% else %>
    <%= render "shared/menu_take_req" %>
    <% end %>
  </div>
  <%= render "shared/footer" %>
</div>