config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  resources :areas
  resources :items do
    collection do
      get 'order'
      get 'check_order'
      get 'crash_order'
      get 'receive_order'
      get 'approval_order'
      get 'my_store'
    end
    resources :chats
  end
  resources :wallets do
    collection do
      get 'check_receipts'
      get 'change_gift'
    end
  end
  resources :orders
  resources :menus do
    collection do
      get 'give'
      get 'take'
      get 'point'
      get 'how_to_use'
    end
  end
  resources :gifts do
    collection do
      get 'watching_ads'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :orders
  has_one :chat

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :wash_power
  belongs_to :status

  validates :wash_power_id, :status_id, :comment, :address, :point, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    my_area
    @items = Item.where(status_id: 2)
    gon.items = @items
  end

  def new
    if user_signed_in?
      @item = Item.new
    else
      redirect_to new_user_session_path
    end
  end

  def create
    item = Item.new(item_params)
    if item.valid?
      Item.create(item_params)
      redirect_to :root
    else
      @item = Item.new(item_params)
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @wash_power = WashPower.find(@item.wash_power_id)
    @status = Status.find(@item.status_id)
  end
  
  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.new(item_params)
    if @item.valid?
      Item.find(params[:id]).update(item_params)
      redirect_to root_path
    else
      @item = Item.find(params[:id])
      render :edit
    end
  end
  
  def order
    #binding.pry
    item = Item.find_by(id: params[:format])
    if current_user.wallet.point >= item.point
      order = Order.new
      order.item_id = item.id
      order.taker = current_user.id
      order.giver = item.user_id
      order.point = item.point
      order.save
      @order_message = "リクエストを送信しました"
    else
      @order_message = "ポイントが不足しています"
    end
  end

  def check_order
    if user_signed_in?
      @orders = Order.where(taker: current_user.id).order(id: "DESC")
    else
      redirect_to new_user_session_path
    end
  end

  def crash_order
    #binding.pry
    order = Order.find(params[:format])
    order.destroy
    @orders = Order.where(taker: current_user.id).order(id: "DESC")
    redirect_to check_order_items_path
  end

  def receive_order
    if user_signed_in?
      @orders = Order.where(giver: current_user.id).order(id: "DESC")
    else
      redirect_to new_user_session_path
    end
  end

  def approval_order
    #binding.pry
    order = Order.find(params[:format].to_i)
    Order.find(params[:format].to_i).update(status: 1)
    taker_receipt = Receipt.new
    taker_receipt.point = (-1)*order.point
    taker_receipt.wallet_id = User.find_by(id: order.taker).wallet.id
    taker_receipt.reason = "サービスを利用しました"
    taker_receipt.save
    giver_receipt = Receipt.new
    giver_receipt.point = order.point
    giver_receipt.wallet_id = User.find_by(id: order.giver).wallet.id
    giver_receipt.reason = "サービス提供のお礼です"
    giver_receipt.save
    @orders = Order.where(giver: current_user.id).order(id: "DESC")
    redirect_to receive_order_items_path
  end
  
  def my_store
    if user_signed_in?
      @items = Item.where(user_id: current_user.id)
    else
      redirect_to new_user_session_path
    end
  end

  private

  def my_area
    if user_signed_in? && Area.find_by(user_id: current_user.id) != nil
      gon.lat = Area.find_by(user_id: current_user.id).latitude
      gon.lng = Area.find_by(user_id: current_user.id).longitude
    else
      gon.lat = nil
      gon.lng = nil
    end
  end

  def item_params
    params.require(:item).permit(:wash_power_id, :status_id, :point, :comment, :address, :user_id, :latitude, :longitude).merge(user_id: current_user.id)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_check_order_content.html.erb
<div class="content">
  <div class="content_header_daj">
    <b>送信したリクエスト履歴</b>
  </div>
  <div class="content_body_M">
    <div>
      <% @orders.each do |o| %>
      <b>
        <% if o.status == 0 %>
        <span style="color:orange;">未承認</span>
        <%= link_to '▶キャンセル', crash_order_items_path(o.id), class: "small_btn", style:"text-decoration: none;" %>
        <% else %>
        <span style="color:cyan;">承認済</span>
        <% end %>
        <%= "#{o.point}P" %>
      </b>
      <%= "@#{o.item.address}" %><br>
      <%= "　　　送信日時：#{o.created_at.strftime("%Y年%m月%d日 %H時%m分")}" %><br>
      <% end %>
    </div>
  </div>
</div>

app/views/items/_edit_content.html.erb
<div class="content">
  <div class="content_body_M_daj">
    <%= form_with(model: @item, local: true) do |f| %>
    洗濯重量　<%= f.collection_select(:wash_power_id, WashPower.all, :id, :name, {include_blank: "---"}) %>まで<br><br>
    看板　　　<%= f.collection_select(:status_id, Status.all, :id, :name, {include_blank: "---"}) %><br><br>
    <%= f.text_field :point, placeholder:"設定ポイント" %>P<br><br>
    <%= f.text_field :address, placeholder:"受付場所" %><br><br>
    <%= f.text_area :comment, placeholder:"コメント" %><br><br>
    <%= f.submit "更新", class:"small_btn btn-shared" %>
    <% end %>
  </div>
  <div class="content_footer">
    <div class="chat_form">

    </div>
  </div>
</div>

app/views/items/_my_store_content.html.erb
<div class="content">
  <div class="content_header_daj">
    <b>提供中のサービス一覧</b>
  </div>
  <div class="content_body_M">
    <table border="1">
      <tr>
        <th style="text-align: center;">リンク</th>
        <th style="text-align: center;">状態</th>
        <th style="text-align: center;">洗濯重量</th>
        <th style="text-align: center;">ポイント</th>
        <th>受付場所</th>
      </tr>
      <% @items.each do |item| %>
      <tr>
        <td style="text-align: center;"><%= link_to '詳細',item_path(item.id), style:"color: white;" %></td>
        <td style="text-align: center;"><%= item.status.name %></td>
        <td style="text-align: center;"><%= item.wash_power.name %></td>
        <td style="text-align: center;"><%= item.point %>P</td>
        <td><%= item.address %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/items/_new_content.html.erb
<div class="content">
  <div class="content_body_M_daj">
    <%= form_with(model: @item, url:items_path, local: true) do |f| %>
    洗濯重量　<%= f.collection_select(:wash_power_id, WashPower.all, :id, :name, {include_blank: "---"}) %>まで<br><br>
    看板　　　<%= f.collection_select(:status_id, Status.all, :id, :name, {include_blank: "---"}) %><br><br>
    <%= f.text_field :point, placeholder:"設定ポイント" %>P<br><br>
    <%= f.text_field :address, placeholder:"受付場所" %><br><br>
    <%= f.text_area :comment, placeholder:"コメント" %><br><br>
    <%= f.submit "登録", class:"small_btn btn-shared" %>
    <% end %>
  </div>
  <div class="content_footer">
    <div class="chat_form">
      <p style="font-size:12px; color:white;">ヒント：あとで変更できます</p><br>
    </div>
  </div>
</div>

app/views/items/_order_content.html.erb
<div class="content">
  <div class="content_body_L">
    <%= "#{@order_message}"%><br>
    <%= link_to 'OK', item_path(params[:format]), class: "btn-shared" %>
  </div>
</div>

app/views/items/_receive_order_content.html.erb
<div class="content">
  <div class="content_header_daj">
    <b>受信したリクエスト履歴</b>
  </div>
  <div class="content_body_M">
    <div>
      <% @orders.each do |o| %>
      <b>
        <% if o.status == 0 %>
        <span style="color:orange;">未承認</span>
        <%= link_to '▶承認', approval_order_items_path(o.id), class: "small_btn", style:"text-decoration: none;" %>
        <% else %>
        <span style="color:cyan;">承認済</span>
        <% end %>
        <%= "#{o.point}P" %>
      </b>
      <%= "@#{o.item.address}" %><br>
      <%= "　　　受信日時：#{o.created_at.strftime("%Y年%m月%d日 %H時%m分")}" %><br>
      <% end %>
    </div>
  </div>
</div>

app/views/items/_show_content.html.erb
<div class="content">
  <div class="content_header_daj">
    <p><%= @status.name %></p>
  </div>
  <div class="content_body_S_daj">
    <br>
    洗濯重量：<%= @wash_power.name %>まで<br><br>
    1回　<%= @item.point %>ポイント<br><br>
    受け渡し場所：<%= @item.address %><br><br>
    出品者：<%= @item.user.email %><br><br>
    コメント：<%= @item.comment %><br><br>
  </div>
  <div class="content_footer">
    <% if @item.user_id == current_user.id %>
    <div class="content_footer_2">
      <%= link_to '編集', edit_item_path, method: :get, class: "btn-shared" %>
    </div>
    <div class="content_footer_2">
      <%= link_to "お問い合わせを確認", new_item_chat_path(@item), class: "btn-shared" %>
    </div>
    <% else %>
    <%= link_to "お問い合わせ", new_item_chat_path(@item), class: "btn-shared" %>
    <% end %>
  </div>
</div>

app/views/items/check_order.html.erb
<div class="outer_frame">
  <%= render "shared/header" %>
  <div class="inner_frame">
    <%= render "check_order_content" %>
    <%= render "shared/menu" %>
  </div>
  <%= render "shared/footer" %>
</div>

app/views/items/index.html.erb
<div class="outer_frame">
  <%= render "shared/header" %>
  <div class="inner_frame">
    <%= render "index_content" %>
    <%= render "shared/menu_top" %>
  </div>
  <%= render "shared/footer" %>
</div>

app/views/items/my_store.html.erb
<div class="outer_frame">
  <%= render "shared/header" %>
  <div class="inner_frame">
    <%= render "my_store_content" %>
    <%= render "shared/menu_give" %>
  </div>
  <%= render "shared/footer" %>
</div>

app/views/items/new.html.erb
<div class="outer_frame">
  <%= render "shared/header" %>
  <div class="inner_frame">
    <%= render "new_content" %>
    <%= render "shared/menu_give" %>
  </div>
  <%= render "shared/footer" %>
</div>

app/views/items/order.html.erb
<div class="outer_frame">
  <%= render "shared/header" %>
  <div class="inner_frame">
    <%= render "order_content" %>
    <%= render "shared/menu_take" %>
  </div>
  <%= render "shared/footer" %>
</div>

app/views/items/receive_order.html.erb
<div class="outer_frame">
  <%= render "shared/header" %>
  <div class="inner_frame">
    <%= render "receive_order_content" %>
    <%= render "shared/menu" %>
  </div>
  <%= render "shared/footer" %>
</div>

app/views/items/show.html.erb
<div class="outer_frame">
  <%= render "shared/header" %>
  <div class="inner_frame">
    <%= render "show_content" %>
    <% if @item.user_id == current_user.id %>
    <%= render "shared/menu_give" %>
    <% else %>
    <%= render "shared/menu_take_req" %>
    <% end %>
  </div>
  <%= render "shared/footer" %>
</div>